### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by MiTRonGTE** [labstructbioinf/pLM-BLAST#2]
After installing packages via `pip install -r requirements.txt` there is a dependency conflict.

ERROR: Cannot install fairscale==0.4.12 and numpy==1.20.1 because these package versions have conflicting dependencies.

fairscale==0.4.12 use numpy>=1.22.0 but in requirements.txt is numpy==1.20.1.

**Comment by Argusmocny** [comment]
thanks for sharing, fixed.
