### ISSUE TITLE
Return results of pre-screening only

### ISSUE THREAD

**Issue by staszekdh** [labstructbioinf/pLM-BLAST#47]
Would it be possible to implement an option/flag in pLM-BLAST to return the pre-screening scores without performing the subsequent time-consuming alignments?

**Comment by Argusmocny** [comment]
I have added an `--only-scan` flag to `scripts/plmblast.py` it will force to save prescreeining results to `ouput` argument. **script will exit after that**. The format of the file is as below:
```bash
{
'queryid1 : {
		{ file: targetfile1, score: scoreval1, condition: True }
               { file: targetfile2, score: scoreval2, condition: False }
}, queryid2 : {
	     { file: targetfile1, score: scoreval1, condition: True }
...
} 
```
Where score is a pre-screening value and condition checks whether quantile threshold criteria is met. Please give me a feedback whether this meets your expectations.

**Comment by NikolasMumm** [comment]
Now everything is working fine, thank you very much
