### ISSUE TITLE
[ERROR] "embeddings.py: error: unrecognized arguments: -proc 4"

### ISSUE THREAD

**Issue by DaRinker** [labstructbioinf/pLM-BLAST#52]
Decided to circle back to pLM to see if I can get it to run more efficiently on my HPC

Git cloned the repo today and am trying to verify behavior before I attempt a massive database build. 

Running with 4 GPUs

Command:
`# FASTA input
python embeddings.py start database.fasta database -embedder pt --gpu -proc 4 -bs 0 --asdir`

Produces:
`$ python embeddings.py start database.fasta database -embedder pt --gpu -proc 4 -bs 0 --asdir
usage: embeddings.py [-h] {start,resume} ...
embeddings.py: error: unrecognized arguments: -proc 4
`

Note that I _**can**_ run  `embeddings.py ` if I remove the `-proc` option

**Comment by DaRinker** [comment]
Wait. just the documentation is wrong.
Looks like the correct parameter should be `-nproc`

**Comment by staszekdh** [comment]
Fixed.
