### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by dc2211** [labstructbioinf/pLM-BLAST#56]
Hello, 
I have been trying to run pLM-BLAST on a "real" scenario, using the ECOD30 database. I have also tried with a custom database of just 10K protein sequences. I have been unable to run a one-vs-all with `plmblast.py`, getting a `Segmentation fault`. I'm using a RTX3090 24gb, 10 CPU. Is this enough?

```
$ python scripts/plmblast.py ECOD30 ross out.hits.csv -cpc 70 -workers 10

OMP: Info #277: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
num cores:  10
loaded database: ECOD30 - in dir mode
/home/projects/pLM-BLAST/alntools/filehandle.py:135: UserWarning: Id column is not unique, using index as id
  warnings.warn("Id column is not unique, using index as id")
loaded query: ross - in dir mode
Pre-screening params: 70.0 quantile, kernel size: 30, stride: 10
Segmentation fault
```

Many thanks

**Comment by staszekdh** [comment]
@dc2211  I see that the issue is marked as resolved, although we would appreciate a note about what the problem was and how you fixed it.
